apiVersion: v1
kind: ConfigMap
metadata:
  name: dm-prov-telco-pin-conf-config
  namespace: {{ .Release.Namespace }}
  labels:
      application: {{ .Chart.Name }}
data:
  pin.conf: |

        #=======================================================================
        # ptr_virtual_time
        # 
        # Enables the use of pin_virtual_time to advance Portal time, and 
        # specifies the shared file for use by all Portal mangers.
        #
        # The entry has 2 values
        #
        # #/Empty     	to disable / enable pin_virtual_time in all pin.conf files
        #		default = #	(disable)
        #
        # <filepath> 	location and name of the pin_virtual_time file shared by all Portal managers.
        #		default = ${PIN_HOME}/lib/pin_virtual_time_file
        #
        #=======================================================================
        #- - pin_virtual_time ${SHARED_VIRTUAL_TIME_FILE}

        #************************************************************************
        # Queue Management Information
        #
        # The entries below specify how this Portal process should manage
        # transactions.
        #
        # For information on tuning the queuing entries to improve performance,
        # see the online document "Portal Configuration and Tuning Guide."
        #************************************************************************
        #
        #========================================================================
        # dm_n_fe
        #
        # Specifies the number of front ends this DM creates and uses.
        #
        # The allowable range of values is:
        #
        #    Minimum = 1
        #    Maximum = 16
        #========================================================================
        - dm dm_n_fe ${DM_PROV_TELCO_NO_FRONT_ENDS}

        #========================================================================
        # dm_bigsize
        #
        # (UNIX only) Specifies the size of shared memory for "big" shared memory structures,
        # such as those used for large searches (those with more than 128 results)
        # or for PIN_FLDT_BUF fields larger than 4 KB.
        #
        # The allowable range of values is:
        #
        #    Minimum = 262144 bytes (256 KB)
        #    Maximum = 206158429184 bytes (Approx. 192 GB)
        #
        # This value cannot be more than the value specified in qm_shmsize, in the
        # qm configuration file.
        #
        # If you get memory errors, increase the value.
        #========================================================================
        - dm dm_bigsize ${DM_PROV_TELCO_SHM_BIGSIZE}

        #========================================================================
        # dm_db_no
        #
        # Specifies the database number for this DM.
        #
        # The format is 0.0.0.n  / 0, where n is your database number.
        # The default database number for the Portal Data Manager (Oracle or
        # SQL Server) is 1. Other default database numbers are:
        #
        #    0.0.0.2   Clear Commerce
        #    0.0.0.2   Paymentech
        #    0.0.0.3   Email Data Manager
        #    0.0.0.4   Taxware DM
        #    0.0.4.1   Activity Log Data Manager
        #    0.0.5.x   LDAP Data Manager
        #========================================================================
        - dm dm_db_no 0.0.10.2 / 0

        #========================================================================
        # dm_logfile
        #
        # Specifies the full path to the log file used by this DM.
        #
        # You can enter any valid path.
        #========================================================================
        - dm dm_logfile ${PIN_LOG_DIR}/dm_prov_telco.pinlog

        #========================================================================
        # dm_max_per_fe
        #
        # Specifies the maximum number of connections for each front end.
        #
        # The allowable range of values is:
        #
        #    Minimum                 = 8
        #    Maximum (in Windows NT) = 63
        #    Maximum (in UNIX)       = 512
        #========================================================================
        - dm dm_max_per_fe ${DM_PROV_TELCO_MAX_PER_FE}

        #========================================================================
        # dm_n_be
        #
        # Specifies the number of back ends this DM creates and uses.
        #
        # The allowable range of values is:
        #
        #    Minimum = 1
        #    Maximum = 256
        #
        # Important: Creating an Portal account requires two connections, one
        #    transaction connection and one regular connection. You must have at
        #    least two back ends for each account you are creating at one time.
        #    See the online document "Portal Configuration and Tuning Guide."
        #========================================================================
        - dm dm_n_be ${DM_PROV_TELCO_NO_BACK_ENDS}

        #========================================================================
        # dm_name
        #
        # Specifies the name of the computer where this DM runs.
        #
        # The name can be:
        #
        #    - (hyphen)                = Portal can use any IP address on the
        #                                  DM computer.
        #
        #    <host name or IP address> = Portal should use a particular IP
        #                                  address on the DM computer.
        #
        # This entry is optional. If you remove or disable it, Portal uses
        # gethostname to find the IP address of the DM computer.
        #========================================================================
        - dm dm_name ${HOSTNAME}

        #========================================================================
        # dm_port
        #
        # Specifies the port number for this DM.
        #
        # This number was assigned to the DM when you installed Portal. If you
        # change the port, make sure the port number does not conflict with
        # another service. This number must be greater than 1000, unless you start
        # the process as root.
        #
        # The CM configuration file must have a corresponding dm_pointer entry
        # with the same port number.
        #========================================================================
        - dm dm_port ${DM_PROV_TELCO_SERVICE_PORT}

        #========================================================================
        # dm_provision_commit_at_prep
        #
        # If this entry is set to 1 then dm_prov_telco will commit the BRM
        # transaction AFTER publishing service order to the agent. If it is set to 0
        # then dm_prov_telco will commit the BRM transaction BEFORE publishing service
        # order # to the agent. Default is 0.
        #========================================================================
        - dm_provision commit_at_prep 0

        #======================================================================
        # dm_provision_connect_retries
        #**********************************************************************
        # Reconnecting to Infranet agent
        #**********************************************************************
        # Specifies the number of times dm_provision tries to retry to
        # connect to the Infranet agent when connecting fails.  Before
        # each retry, dm_provision waits the interval specified in
        # connect_retry_interval.
        #
        #======================================================================
        - dm_provision connect_retries 1

        #======================================================================
        # dm_provision_connect_retry_interval
        #
        # Specifies how many seconds to wait before retrying to connect
        # to the Infranet agent when connecting fails.  0 means no wait.
        #
        #======================================================================
        - dm_provision connect_retry_interval 2

        #========================================================================
        # dm_provision_loglevel
        #
        # Specifies how much information the dm_prov_telco logs.
        #
        # The value for this entry can be:
        #
        #    0 = no logging
        #    1 = (Default) log error messages only
        #    2 = log error messages and warnings
        #    3 = log error, warning, and debugging messages
        #========================================================================
        - dm loglevel ${LOG_LEVEL}

        #========================================================================
        # dm_provision_prov_ptr
        #
        # Specifies address of the agent which publishes the service order
        #
        # Each prov_ptr includes two values:
        #
        #    -- the IP address or host name of the agent computer
        #    -- the port number of the agent
        #========================================================================
        - dm_provision prov_ptr ip ${DM_PROV_AGENT_HOSTNAME} ${DM_PROV_AGENT_PORT}

        #======================================================================
        # dm_provision_prov_timeout
        #
        # Specifies a timeout when waiting for responses from Infranet
        # agent.  The value is specified in seconds.  0 means no timeout.
        # This timeout is mostly useful for "confirmed" orders, where
        # the response is not returned until the order has been completely
        # processed.
        #
        #======================================================================
        - dm_provision prov_timeout 20

        #========================================================================
        # dm_restart_children
        #
        # Specifies whether to replace child processes.
        #
        # The value for this entry can be:
        #
        #    0 = Do not replace child processes.
        #    1 = (Default) The DM master process replaces any child DM processes
        #          that fail.
        #========================================================================
        - dm dm_restart_children 1

        #- dm dm_restart_delay 0

        #========================================================================
        # dm_shmsize
        #
        # (UNIX only) Specifies the size of shared memory segment, in bytes, that
        # is shared between the front ends and back ends for this DM.
        #
        # The allowable range of values is:
        #
        #    Minimum = 2097152 bytes (2 MB)
        #    Maximum = 274877905920 bytes  (Approx. 256 GB)
        #
        # Solaris: You must edit the /etc/system file because the system default
        #          for the maximum allowable shared-memory segment is too low.
        #          See "Problems with memory management" in the online
        #          documentation.
        #========================================================================
        - dm dm_shmsize ${DM_PROV_TELCO_SHM_SIZE}


        #========================================================================
        # dm_sm_obj
        #
        # Specifies a pointer to the Storage Manager shared library that contains
        # the code that the Data Manager uses to interact with the database.
        #
        # Portal was set up with the correct file during installation.
        # DO NOT change this configuration entry.
        #========================================================================
        - dm dm_sm_obj ${PIN_HOME}/sys/dm_prov_telco/dm_prov_telco.so

        #========================================================================
        # dm_trans_be_max
        #
        # Specifies the maximum number of back ends that can be used for
        # processing transactions.
        #
        # By default, as many as half of the back ends can process transactions.
        # To increase the number of back ends for processing transactions, remove
        # the crosshatch (#) from the beginning of the line for this entry and
        # enter the number you want. The number must be no greater than the total
        # number of back ends (dm_n_be).
        #========================================================================
        - dm dm_trans_be_max ${DM_PROV_TELCO_MAX_PER_BE}


        #========================================================================
        # dm_trans_timeout
        #
        # Specifies the timeout value, in minutes, to be used by dm back-end
        # processes in receiving the next opcode of a transaction.
        #
        # The value for this entry can be:
        #
        #    0 or less      = (Default) A DM back-end process waits forever
        #                       for the next opcode request.
        #    greater than 0 = A DM back-end process waits until the specified
        #                       number of minutes have gone by and then, if no
        #                       opcode request has arrived, aborts the transaction.
        #
        # This parameter takes effect if and only if a DM back-end process is
        # processing a transaction.
        #========================================================================
        - dm dm_trans_timeout 0

        #========================================================================
        # enable_ssl
        #
        # Specifies whether TLS will be enabled for PCM connections
        #
        #    0 - TLS is disabled.
        #    1 - TLS is enabled.
        #
        ##========================================================================
        - dm enable_ssl ${ENABLE_SSL}

        #========================================================================
        # extra_search
        #
        # Specifies if we want to do extra search count(*) on sub tables
        # so we can allocate memory optimally
        #
        # The value for this entry can be:
        #
        #    0                  = (Default) not do the extra search
        #    1                  = do the extra search and allocate memory optimally.
        ##========================================================================
        - dm extra_search 0

        #========================================================================
        # sm_svcname
        #
        # Database service name.
        #
        # This is the service_name you used to define SQL*NET alias (sm_database)
        # in the tnsnames.ora file when you set up the Oracle database.
        # By default, this entry was not configured when you install Infranet.
        # You should only enable this when you need 10g RAC HA support.
        #========================================================================
        #- dm sm_svcname <service_name>
