---
### Deployment Descriptor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-vertex-deploy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ocbrm.dm_vertex.deployment.replicaCount }}
  selector:
    matchLabels:
      application: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        application: {{ .Chart.Name }}
        component: oms-dm_vertex
    spec:
      containers:
      - name: dm-vertex
        image: "{{ .Values.imageRepository }}{{ .Values.ocbrm.dm_vertex.deployment.imageName }}:{{ .Values.ocbrm.dm_vertex.deployment.imageTag }}"
        {{- if eq .Values.ocbrm.virtual_time.enabled true }}
        command: ["/bin/sh"]
        args: ["-c", "sleep 10;/oms/entrypoint.sh dm_vertex"]
        {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: dm-vertex-port
            containerPort: {{ .Values.ocbrm.dm_vertex.deployment.port }}
        env:
        - name: INIT_DB
          value: "{{ .Values.ocbrm.init_database }}"
        - name: TZ
          value: "{{ .Values.ocbrm.TZ }}"
        - name: CMAP_DEBUG
          value: "0x0001"
        - name: CM_DEBUG
          value: "0x0001"
        - name: DM_DEBUG
          value: "0x0001"
        - name: DM_DEBUG2
          value: "0x0001"
        - name: DM_DEBUG3
          value: "0x0001"
        - name: PIN_LOG_DIR
          value: "{{ .Values.ocbrm.logDir }}"
        - name: DM_VERTEX_CTQ_SM_OBJ
          value: {{ .Values.ocbrm.dm_vertex.deployment.ctqSmObj }}
        - name: DM_VERTEX_CTQ_CFG_NAME
          value: {{ .Values.ocbrm.dm_vertex.deployment.ctqCfgName }}
        - name: TNS_ADMIN
          value: "/oms/ora_k8/"
        - name: DM_VERTEX_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: DM_VERTEX_SERVICE_PORT
        - name: DM_VERTEX_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: DM_VERTEX_SERVICE_HOST
        - name: QUANTUM_DB_SOURCE
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: QUANTUM_DB_SOURCE
        - name: QUANTUM_DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: QUANTUM_DB_SERVER
        - name: QUANTUM_DB_USER
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: QUANTUM_DB_USER
        - name: QUANTUM_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oms-schema-password
              key: quantum_db_password
        - name: LIBRARYEXTENSION
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: LIBRARYEXTENSION
        - name: VIRTUAL_TIME_SETTING
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: VIRTUAL_TIME_SETTING
        - name: VIRTUAL_TIME_ENABLED
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: VIRTUAL_TIME_ENABLED
        - name: CLIENT_WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oms-schema-password
              key: client_wallet_password
        - name: OLD_ROOT
          valueFrom:
            secretKeyRef:
              name: oms-schema-password
              key: old_root
        - name: OLD_CLIENT
          valueFrom:
            secretKeyRef:
              name: oms-schema-password
              key: old_client
        - name: ROOT_WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oms-schema-password
              key: root_wallet_password
        - name: SERVER_WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oms-schema-password
              key: server_wallet_password
        - name: DM_VERTEX_CTQ_CFG_PATH
          valueFrom:
            configMapKeyRef:
              name: oms-common-config
              key: DM_VERTEX_CTQ_CFG_PATH
        - name: SHARED_VIRTUAL_TIME_FILE
          value: {{ .Values.ocbrm.virtual_time.pvt }}/pin_virtual_time_file
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
        volumeMounts:
        - name: dm-vertex-pin-conf-volume
          mountPath: /oms/pin.conf.tmpl
          subPath: pin.conf
        - name: oms-logs
          mountPath: {{ .Values.ocbrm.logDir }}
        - name: virtual-time-volume
          mountPath: /oms/virtual_time/shared
        - name: dm-vertex-tnsnames-ora-volume
          mountPath: /oms/ora_k8/
        - name: dm-vertex-ctq-cfg
          mountPath: {{ .Values.ocbrm.dm_vertex.deployment.ctqCfg }}
      hostname: dm-vertex
      dnsPolicy: ClusterFirst
      volumes:
        - name: dm-vertex-pin-conf-volume
          configMap:
            name: dm-vertex-pin-conf-config
        - name: oms-logs
          emptyDir: {}
        - name: virtual-time-volume
          persistentVolumeClaim:
            claimName: virtual-time
        - name: dm-vertex-tnsnames-ora-volume
          configMap:
            name: db-config
            items:
              - key: tnsnames.ora
                path: tnsnames.ora
              - key: sqlnet.ora
                path: sqlnet.ora
        - name: dm-vertex-ctq-cfg
          persistentVolumeClaim:
            claimName: {{ .Values.ocbrm.dm_vertex.ctqdir.pvc }}

---

apiVersion: v1
kind: Service
metadata:
  name: dm-vertex
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Chart.Name }}
spec:
  selector:
    component: oms-dm_vertex
  ports:
    - name: dm-vertex-port
      port: {{ .Values.ocbrm.dm_vertex.deployment.port }}
  type: {{ .Values.ocbrm.dm_vertex.service.type }}
