kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: {{ .Values.ocbrm.dm_vertex.ctqdir.pvc }}
 labels:
   application: {{ .Chart.Name }}
spec:
 storageClassName: {{ .Values.ocbrm.storage_class.name }}
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: {{ .Values.ocbrm.dm_vertex.ctqdir.storage }}

