kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: {{ .Values.ocbrm.realtime_pvc.pvc }}
 namespace: {{ .Release.Namespace }}
 labels:
   application: {{ .Chart.Name }}
spec:
 storageClassName: {{ .Values.ocbrm.storage_class.name }}
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: {{ .Values.ocbrm.realtime_pvc.storage }}

