apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.ocboc.boc.secretKeyStore.name }}
    namespace: {{ .Release.Namespace }} 
type: Opaque
data:
    {{- (.Files.Glob "keystore_boc/*").AsSecrets | nindent 4 }}
