apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ocboc.boc.service.name }}
    namespace: {{ .Release.Namespace }} 
    label:
        app.kubernetes.io/name: {{ .Values.ocboc.boc.labels.name }}
        app.kubernetes.io/version: {{ .Values.ocboc.boc.labels.version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    selector:
        app.kubernetes.io/name: {{ .Values.ocboc.boc.labels.name }}
    ports:
    ports:
    {{- if eq .Values.ocboc.boc.configEnv.isSSLEnabled true }}
    -   name: boc-port-https
        port: {{ .Values.ocboc.boc.configEnv.httpsPort }}
        protocol: TCP
        {{- if eq .Values.ocboc.boc.configEnv.isAdminPortEnabled true }}
    -   name: boc-port-admin
        port: {{ .Values.ocboc.boc.configEnv.adminPort }}
        protocol: TCP
        {{- end }}
    {{- else }}
    -   name: boc-port-http
        port: {{ .Values.ocboc.boc.configEnv.httpPort }}
        protocol: TCP
    {{- end }}
    type: {{ .Values.ocboc.boc.service.type }}
