apiVersion: v1
kind: ConfigMap
metadata:
  name: dm-fusa-config
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Chart.Name }}
data:
  DMF_BATCH_PORT: "8780"
  DMF_BATCH_SRVR: fusa-simulator
  DMF_ONLINE_PORT: "9780"
  DMF_ONLINE_SRVR: fusa-simulator
  DMF_TOKEN_ENABLED: "1"
  DMF_CONNECT_RETRYS: "100"
  DMF_SD_DESCRIPTOR_FLAG: "0"
  DMF_SD_MERCHANT: test
  DMF_MERCHANT_DBA: XXXXXX
  DMF_MERCHANT_PDT: XXXXXX
  DMF_MERCHANT_PHONE: 800-555-1234
  DMF_BATCH_TIMEOUT: "600"
  DMF_FUSA_TIMEOUT: "600"
  DMF_TLS_ENABLED: "1"
  DMF_MERCHANT: test
  DMF_MERCHANT_NUM_124: "050505"
  DMF_MERCHANT_NUM_250: "050506"
  DMF_MERCHANT_NUM_280: "050507"
  DMF_MERCHANT_NUM_826: "050508"
  DMF_MERCHANT_NUM_840: "050509"
  DMF_MERCHANT_NUM_978: "050510"
  DMF_PID: "090909"
  DMF_SID: "090909"
  DMF_QM_BIGSIZE: 1M 
  DMF_QM_SHMSIZE: 6M
  DMF_QM_MAX_PER_FE: "16"
  DMF_QM_PORT: "{{ .Values.ocbrm.dm_fusa.deployment.port }}"
  DMF_QM_RESTART_CHILDREN: "1"
  DMF_QM_DEBUG: "0xFF"
  DMF_QM_DEBUG_FRONT: "0xFF"
  DMF_QM_DEBUG_BACK: "0xFF"
  SERVICE_FQDN: dm-fusa
