apiVersion: v1
kind: ConfigMap
metadata:
  name: dm-vertex-pin-conf-config
  labels:
      application: oms
data:
  pin.conf: |
    #************************************************************************
    # Configuration File for BRM with Vertex STQ and CTQ
    #
    # This configuration file is automatically installed and configured with
    # default values during the BRM installation. You can edit this file to:
    #   -- change the default values of the entries.
    #   -- disable an entry by inserting a crosshatch (#) at the start of
    #        the line.
    #   -- enable a commented entry by removing the crosshatch (#).
    #
    # Before you make any changes to this file, save a backup copy.
    #
    # When editing this file, follow the instructions in each section.
    # For more information on the general syntax of configuration entries,
    # see "Reference Guide to BRM Configuration Files" in the BRM online
    # documentation.
    #************************************************************************
    
    
    #======================================================================
    #
    # You can edit this file to suit your specific configuration:
    #  -- You can change the default values of an entry.
    #  -- You can exclude an optional entry by adding the # symbol
    #     at the beginning of the line.
    #  -- You can include a commented entry by removing the # symbol.
    #
    # Before you make any changes to this file, save a backup copy.
    #
    # To edit this file, follow the instructions in the commented sections.
    # For more information on the general syntax of configuration entries,
    # see "Reference Guide to Portal Configuration Files" in the Portal
    # online documentation.
    #======================================================================
    
    #=======================================================================
    # ptr_virtual_time
    #
    # Enables the use of pin_virtual_time to advance Portal time, and
    # specifies the shared file for use by all Portal mangers.
    #
    # The entry has 2 values
    #
    # #/Empty       to disable / enable pin_virtual_time in all pin.conf files
    #               default = #     (disable)
    #
    # <filepath>    location and name of the pin_virtual_time file shared by all Portal managers.
    #               default = ${PIN_HOME}/lib/pin_virtual_time_file
    #
    #=======================================================================
    #- - pin_virtual_time ${SHARED_VIRTUAL_TIME_FILE}    
    
    
    #========================================================================
    # CTQ Configuration Name
    #
    # Specifies the configuration name from the ctqcfg.xml configuration file.
    # Applicable to CommTax (CTQ) only.
    #========================================================================
    # - dm_vertex commtax_config_name ${DM_VERTEX_CTQ_CFG_NAME}
    
    
    #========================================================================
    # CTQ Configuration Path
    #
    # Specifies the location of the CTQ configuration file (ctqcfg.xml).
    # Applicable to CommTax (CTQ) only.
    #========================================================================
    # - dm_vertex commtax_config_path ${DM_VERTEX_CTQ_CFG_PATH}
    
    
    #========================================================================
    # qm_n_fe
    #
    # Specifies the number of front ends the program creates and uses.
    #
    # The allowable range of values is:
    #
    #    Minimum = 1
    #    Maximum = 16
    #
    # Note: For a credit-card processing data manager, set this value to 1.
    #========================================================================
    - dm_vertex qm_n_fe 4
    
    
    #========================================================================
    # qm_bigsize
    #
    # (UNIX only) Specifies the size of shared memory for "big" shared-memory
    # structures, such as those used for searches.
    #
    # Note: On Windows NT systems, Portal ignores this entry.
    #
    # The allowable range of values is:
    #
    #    Minimum = 256K
    #    Maximum = 512M
    #
    # This value cannot be more than the value specified in qm_shmsize.
    #
    # If you get memory errors, increase the value.
    #========================================================================
    - dm_vertex qm_bigsize 512k
    
    
    #========================================================================
    # Queue Management Debugging
    #
    # The entries below specify which debugging information is printed to the
    # program's log file.
    #
    # qm_debug       = print debugging information for all daemons that use
    #                    queue management
    # qm_debug_front = print debugging information for the front ends of
    #                    this daemon only
    # qm_debug_back  = print debugging information for the back ends of
    #                    this daemon only
    #
    # To use one or more of these entries, remove the crosshatch (#) from the
    # start of the line and enter a valid value or combination of values in
    # hexadecimal format.
    #
    # For the main debugging entry:
    #
    #    1 = Print detailed error information.
    #    2 = Print main loop tracing.
    #    4 = Print transaction tracing.
    #
    # For the front-end and back-end debugging entries:
    #
    #    1 = Print information on new connections.
    #    2 = Print input information.
    #    4 = Print operation done information.
    #    8 = Print output information.
    #========================================================================
    #- dm_vertex qm_debug           0x07    # example: print all debug info
    #- dm_vertex qm_debug_front     0x0F    # example: print all debug info, front end
    #- dm_vertex qm_debug_back              0x0F    # example: print all debug info, back end
    
    
    #========================================================================
    # qm_logfile
    #
    # Specifies the full path to the log file used by this Portal process.
    #
    # You can enter any valid path.
    #========================================================================
    - dm_vertex qm_logfile ${PIN_LOG_DIR}/dm_vertex.pinlog
    
    
    #========================================================================
    # qm_max_per_fe
    #
    # Specifies the maximum number of connections for each front end.
    #
    # The allowable range of values is:
    #
    #    Minimum = 8
    #    Maximum = 128
    #========================================================================
    - dm_vertex qm_max_per_fe 16
    
    
    #========================================================================
    # qm_n_be
    #
    # Specifies the number of back ends the program creates and uses.
    #
    # The allowable range of values is:
    #
    #    Minimum = 1
    #    Maximum = 256
    #
    # Note: For dm_fusa, if you use fusamux, set this value between 4 and 8.
    #       If you don▒t use fusamux, set this value to 2 (one for a single
    #       batch and one for online processing).
    #========================================================================
    - dm_vertex qm_n_be 8
    
    
    #========================================================================
    # qm_port
    #
    # Specifies the hostname/IP address and port number for this process.
    #example
    #- qm_process qm_port myhost.com 1234
    #
    # This number was assigned to this process when you installed Portal. If
    # you change the port, make sure the port number does not conflict with
    # another service. This number must be greater than 1000, unless you start
    # the process as root.
    #
    # The CM configuration file must have a corresponding dm_pointer entry
    # with the same port number.
    #========================================================================
    - dm_vertex qm_port  ${DM_VERTEX_SERVICE_HOST} ${DM_VERTEX_SERVICE_PORT}
    
    
    
    #========================================================================
    # qm_restart_children
    #
    # Specifies whether to replace child processes.
    #
    # The value for this entry can be:
    #
    #    0 = The DM doesn't replace child processes.
    #    1 = (Default) The DM master process replaces any child DM processes
    #          that fail.
    #
    # You might set this value to 0 for testing, but it should be 1 for
    # production use.
    #========================================================================
    - dm_vertex qm_restart_children 0
    
    
    #========================================================================
    # qm_shmsize
    #
    # (UNIX only) Specifies the size of the shared-memory segment that is
    # shared between the front ends and back ends for this Portal process.
    #
    # Note: On Windows NT systems, Portal ignores this entry.
    #
    # Use the suffix "K" to express the memory in kilobytes (units of 1024
    # bytes) or the suffix "M" to express the memory in megabytes (units of
    # 1024 kilobytes). For example, the entry "6M" means 6291456 bytes.
    #
    # The allowable range of values is:
    #
    #    Minimum = 1M
    #    Maximum = 512M
    #
    # Solaris: You must edit the /etc/system file, because the system default
    #     for the maximum allowable shared-memory segment is too low.
    #     See "Problems with memory management" in the online documentation.
    #========================================================================
    - dm_vertex qm_shmsize 4M
    
    
    #======================================================================
    # CTQ Debug Logging
    #
    # If specified, uses the CTQ API to log debug information (into the
    # specified filename) about the current transaction to be processed
    # for tax calculation.
    #
    # To use enable CTQ debug logging, remove the crosshatch (#) from the
    # start of this entry's line.
    #======================================================================
    # - dm_vertex commtax_logfile ./ctq_dbg.log
    
    
    #======================================================================
    # CTQ Storage Manager
    #
    # Specifies the Storage Manager shared library that the Data Manager
    # uses to interact with a particular version of the Vertex CTQ system.
    # For example, use dm_vertex_ctq10106 to interact with CTQ v1.01.06.
    # Current values can be:
    #   dm_vertex_ctq10013, dm_vertex_ctq10106, dm_vertex_ctq20005
    #======================================================================
    #- dm_vertex commtax_sm_obj ${DM_VERTEX_CTQ_SM_OBJ}
    
    
    #========================================================================
    # CTQ Register Database
    #
    # Logs the transaction into the Register database.
    #
    # The Register database contains all transactions that are returned from
    # CTQ, and can be used to create audit-trail reports. If you need
    # to use the Register DB, remove the crosshatch (#) from the start of
    # this entry's line.
    #========================================================================
    #- dm_vertex commtaxdb_register -
    
    
    #======================================================================
    # STQ Debug Logging
    #
    # If specified, uses the STQ API to log debug information (into the
    # specified filename) about the current transaction to be processed
    # for tax calculation.
    #
    # To use enable STQ debug logging, remove the crosshatch (#) from the
    # start of this entry's line.
    #======================================================================
    #- dm_vertex quantum_logfile ${PIN_HOME}/sys/dm_vertex/qsut_dbg.log
    
    
    #======================================================================
    # STQ Storage Manager
    #
    # Specifies the Storage Manager shared library that the Data Manager
    # uses to interact with a particular version of the Vertex STQ system.
    # For example, use dm_vertex_stq316 to interact with STQ v3.1.6.
    # Current values can be:
    #   dm_vertex_stq316, dm_vertex_stq3221, dm_vertex_stq406, dm_vertex_stq50
    #======================================================================
    #- dm_vertex quantum_sm_obj ./dm_vertex_stq50${LIBRARYEXTENSION}
    
    
    #========================================================================
    # STQ Database Connection Parameters
    #
    # Specify the connection parameters for Sales & Use (STQ) system.
    #
    #   quantumdb_source: The name of the Oracle user in whose schema the STQ
    #                     tables reside. This parameter is required if the default
    #                     tablespace for the user Id and password parameters is
    #                     not the same tablespace that contains the STQ tables.
    #                     For ISAM database this parameter is simply the directory
    #                     where the database file reside.
    #   quantumdb_server: The network identifier for the Oracle database on
    #                     the server system.
    #                     This parameter should be commented for ISAM database.
    #   quantumdb_user:   Identifies the user as a valid Oracle login.
    #                     This parameter should be commented for ISAM database.
    #   quantumdb_passwd: The identifier that uniquely identifies the user.
    #                     This parameter should be commented for ISAM database.
    #========================================================================
    - dm_vertex  quantumdb_source  ${QUANTUM_DB_SOURCE}
    - dm_vertex  quantumdb_server  ${QUANTUM_DB_SERVER}
    - dm_vertex  quantumdb_user    ${QUANTUM_DB_USER}
    - dm_vertex  quantumdb_passwd  ${QUANTUM_DB_PASSWORD}
    
    
    #========================================================================
    # STQ Register Database
    #
    # Logs an audit trail of invoices in the Register database.
    #
    # The Register database contains tax rules, rates, results, and other
    # information returned from Quantum, and can be used to create audit-trail
    # reports. If you need to use the Register DB, remove the crosshatch (#)
    # from the start of this entry's line.
    #========================================================================
    #- dm_vertex quantumdb_register -
    
    
    #======================================================================
    # tax_rate_precision
    #
    # If specified, precision for tax rate will have given decimal places.
    # By default, the value will be 5. Currently, this entry applies to
    # CTQ tax rate decimal precision only.
    #
    # Enable the below entry to change the tax rate decimal precision.
    #======================================================================
    #- dm_vertex tax_rate_precision 5
    
    
    #======================================================================
    # use_charge_to_category_codes
    #
    # If specified, use the value as the Primary Place of Use (PPU) location
    # and override the 2/3 rule as per the MTSA. If entry is not set, the
    # value is defaulted to 10 (Wireless).  The format is:
    #   - dm_vertex use_charge_to_category_codes <ChargeTo>
    #
    # To specify the ChargeTo, uncomment this entry.
    #======================================================================
    #- dm_vertex use_charge_to_category_codes 10

    #========================================================================
    # enable_ssl
    #
    # Specifies whether TLS will be enabled for PCM connections
    #
    #    0 - TLS is disabled.
    #    1 - TLS is enabled.
    #
    #========================================================================
    - dm enable_ssl ${ENABLE_SSL}

