apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-fusa-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Chart.Name }} 
spec:
  replicas: {{ .Values.ocbrm.dm_fusa.deployment.replicaCount }}
  selector:
    matchLabels:
      application: {{ .Chart.Name }}
  template: 
    metadata: 
      labels:
        application: {{ .Chart.Name }}
        component: dm-fusa
    spec:
      containers:
        - name: dm-fusa
          image: "{{.Values.imageRepository}}{{.Values.ocbrm.dm_fusa.deployment.imageName}}:{{.Values.ocbrm.dm_fusa.deployment.imageTag}}"
          imagePullPolicy: {{.Values.ocbrm.imagePullPolicy}}
          workingDir: /oms/sys/dm_fusa
          command: ["/bin/sh"]
          {{- if eq .Values.ocbrm.virtual_time.enabled true }}
          args: ["-c", "sleep 10;/oms/entrypoint.sh dm_fusa"]
          {{- else }}
          args: ["-c", "/oms/entrypoint.sh dm_fusa"]
          {{- end }}
          env:
          {{- if eq .Values.ocbrm.existing_database true }}
          - name: BRM_WALLET
            value: "/oms/client"
          {{- end }}
          - name: INIT_DB
            value: "{{ .Values.ocbrm.init_database }}"
          - name: TZ
            value: "{{ .Values.ocbrm.TZ }}"
          - name: BINARY
            value: dm_fusa
          - name: PIN_LOG_DIR
            value: "{{ .Values.ocbrm.logDir }}"
          - name: DMF_BATCH_PORT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_BATCH_PORT
          - name: DMF_BATCH_SRVR
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_BATCH_SRVR
          - name: DMF_ONLINE_PORT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_ONLINE_PORT
          - name: DMF_ONLINE_SRVR
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_ONLINE_SRVR
          - name: DMF_TOKEN_ENABLED
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_TOKEN_ENABLED
          - name: DMF_CONNECT_RETRYS
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_CONNECT_RETRYS
          - name: DMF_SD_DESCRIPTOR_FLAG
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_SD_DESCRIPTOR_FLAG
          - name: DMF_SD_MERCHANT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_SD_MERCHANT
          - name: DMF_MERCHANT_DBA
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_DBA
          - name: DMF_MERCHANT_PDT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_PDT
          - name: DMF_MERCHANT_PHONE
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_PHONE
          - name: DMF_ENABLE_SSL
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: ENABLE_SSL
          - name: DMF_BATCH_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_BATCH_TIMEOUT
          - name: DMF_FUSA_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_FUSA_TIMEOUT
          - name: DMF_TLS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_TLS_ENABLED
          - name: DMF_MERCHANT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT
          - name: DMF_MERCHANT_NUM_124
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_NUM_124
          - name: DMF_MERCHANT_NUM_250
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_NUM_250
          - name: DMF_MERCHANT_NUM_280
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_NUM_280
          - name: DMF_MERCHANT_NUM_826
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_NUM_826
          - name: DMF_MERCHANT_NUM_840
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_NUM_840
          - name: DMF_MERCHANT_NUM_978
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_MERCHANT_NUM_978
          - name: DMF_PID
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_PID
          - name: LIBRARYEXTENSION
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: LIBRARYEXTENSION
          - name: LIBRARYPREFIX
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: LIBRARYPREFIX
          - name: DMF_PID_PWD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: dmf_pid_pwd
          - name: DMF_SID
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_SID
          - name: DMF_SID_PWD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: dmf_sid_pwd
          - name: DMF_QM_BIGSIZE
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_BIGSIZE
          - name: DMF_QM_SHMSIZE
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_SHMSIZE
          - name: DMF_QM_MAX_PER_FE
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_MAX_PER_FE
          - name: DMF_QM_PORT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_PORT
          - name: DMF_QM_RESTART_CHILDREN
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_RESTART_CHILDREN
          - name: DMF_QM_DEBUG
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_DEBUG
          - name: DMF_QM_DEBUG_FRONT
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_DEBUG_FRONT
          - name: DMF_QM_DEBUG_BACK
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: DMF_QM_DEBUG_BACK
          - name: SERVICE_FQDN
            valueFrom:
              configMapKeyRef:
                name: dm-fusa-config
                key: SERVICE_FQDN
          - name: OLD_CLIENT
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: old_client
          - name: OLD_ROOT
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: old_root
          - name: CLIENT_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: client_wallet_password
          - name: ROOT_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: root_wallet_password
          - name: SERVER_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: server_wallet_password
          - name: BRM_CRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: brm_crypt_key
          - name: VIRTUAL_TIME_ENABLED
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: VIRTUAL_TIME_ENABLED
          - name: VIRTUAL_TIME_SETTING
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: VIRTUAL_TIME_SETTING
          - name: SHARED_VIRTUAL_TIME_FILE
            value: {{ .Values.ocbrm.virtual_time.pvt }}/pin_virtual_time_file
          volumeMounts:
            {{- if eq .Values.ocbrm.existing_database true }}
            - name: wallet-pvc
              mountPath: /oms/client
            {{- end }}
            - name: dm-fusa-pin-conf-volume
              mountPath: /oms/pin.conf.tmpl
              subPath: pin.conf
            - name: oms-dm-fusa-temp
              mountPath: /oms/fusa_temp
            - name: oms-logs
              mountPath: {{ .Values.ocbrm.logDir }}
            - name: virtual-time-volume
              mountPath: {{ .Values.ocbrm.virtual_time.pvt }}
      volumes:
        {{- if eq .Values.ocbrm.existing_database true }}
        - name: wallet-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.ocbrm.wallet.pvc }}
        {{- end }}
        - name: dm-fusa-pin-conf-volume 
          configMap:
            name: dm-fusa-pin-conf-config
        - name: oms-dm-fusa-temp 
          persistentVolumeClaim:
            claimName: {{ .Values.ocbrm.dm_fusa.tempdir.pvc }}
        - name: oms-logs
          emptyDir: {}
        - name: virtual-time-volume
          persistentVolumeClaim:
            claimName: virtual-time

---

apiVersion: v1
kind: Service
metadata:
  name: dm-fusa
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    component: dm-fusa
  ports:
    - name: dm-fusa-port
      port: {{ .Values.ocbrm.dm_fusa.deployment.port }} 
