apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusa-simulator-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Chart.Name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      application: {{ .Chart.Name }}
  template: 
    metadata: 
      labels:
        application: {{ .Chart.Name }}
        component: fusa-simulator
    spec:
      containers:
        - name: fusa-simulator
          image: "{{.Values.imageRepository}}answer:{{.Values.ocbrm.dm_fusa.deployment.simulatorTag}}"
          imagePullPolicy: {{.Values.ocbrm.imagePullPolicy}}
          workingDir: /oms/apps/fusa_server
          command: ["/bin/sh"]
          {{- if eq .Values.ocbrm.virtual_time.enabled true }}
          args: ["-c", "sleep 10;/oms/entrypoint.sh answer"]
          {{- else }}
          args: ["-c", "/oms/entrypoint.sh answer"]
          {{- end }}
          ports:
            - name: answer-s
              containerPort: 9780
            - name: answer-b
              containerPort: 8780
          env:
          {{- if eq .Values.ocbrm.existing_database true }}
          - name: BRM_WALLET
            value: "/oms/client"
          {{- end }}
          - name: INIT_DB
            value: "{{ .Values.ocbrm.init_database }}"
          - name: BINARY
            value: answer
          - name: PIN_LOG_DIR
            value: "{{ .Values.ocbrm.logDir }}"
          - name: FUSA_ANS_S_AVS
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_ANS_S_AVS
          - name: FUSA_ANS_B_DROP_LINE
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_ANS_B_DROP_LINE
          - name: FUSA_ANS_B_NO_RESPONSE
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_ANS_B_NO_RESPONSE
          - name: FUSA_ANS_B_V_CODE
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_ANS_B_V_CODE
          - name: FUSA_ANS_S_S_CODE
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_ANS_S_S_CODE
          - name: FUSA_ANS_S_V_CODE
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_ANS_S_V_CODE
          - name: FUSA_SIMULATION_LEVEL
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_SIMULATION_LEVEL
          - name: FUSA_SIM_WAIT
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_SIM_WAIT
          - name: FUSA_SIM_S_LOGLEVEL
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_SIM_S_LOGLEVEL
          - name: FUSA_SIM_B_LOGLEVEL
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: FUSA_SIM_B_LOGLEVEL
          - name: SERVICE_FQDN
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: SERVICE_FQDN
          - name: ANSWER_TLS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: fusa-sim-config
                key: ANSWER_TLS_ENABLED
          - name: LIBRARYEXTENSION
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: LIBRARYEXTENSION
          - name: LIBRARYPREFIX
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: LIBRARYPREFIX
          - name: OLD_ROOT
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: old_root
          - name: OLD_CLIENT
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: old_client
          - name: CLIENT_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: client_wallet_password
          - name: ROOT_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: root_wallet_password
          - name: SERVER_WALLET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: server_wallet_password
          - name: BRM_CRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: oms-schema-password
                key: brm_crypt_key
          - name: VIRTUAL_TIME_ENABLED
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: VIRTUAL_TIME_ENABLED
          - name: VIRTUAL_TIME_SETTING
            valueFrom:
              configMapKeyRef:
                name: oms-common-config
                key: VIRTUAL_TIME_SETTING
          - name: SHARED_VIRTUAL_TIME_FILE
            value: {{ .Values.ocbrm.virtual_time.pvt }}/pin_virtual_time_file
          volumeMounts:
            {{- if eq .Values.ocbrm.existing_database true }}
            - name: wallet-pvc
              mountPath: /oms/client
            {{- end }}
            - name: fusa-sim-pin-conf-volume
              mountPath: /oms/pin.conf.tmpl
              subPath: pin.conf
            - name: virtual-time-volume
              mountPath: {{ .Values.ocbrm.virtual_time.pvt }}
      volumes:
        {{- if eq .Values.ocbrm.existing_database true }}
        - name: wallet-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.ocbrm.wallet.pvc }}
        {{- end }}
        - name: fusa-sim-pin-conf-volume 
          configMap:
            name: fusa-simulator-pin-conf-config
        - name: oms-logs
          emptyDir: {}
        - name: virtual-time-volume
          persistentVolumeClaim:
            claimName: virtual-time

---

apiVersion: v1
kind: Service
metadata:
  name: fusa-simulator
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    component: fusa-simulator
  ports:
    - name: answer-s-port
      port: 9780 
    - name: answer-b-port
      port: 8780 

