apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oms-schema-password
  namespace: {{ .Release.Namespace }}
  labels:
      application: {{ .Chart.Name }}
data:
  # BRM root password
  brm_root_password: {{ .Values.ocbrm.brm_root_pass }}

  #DB Schema Password
  oms_schema_password: {{ .Values.ocbrm.db.schemapass }}

  pipeline_schema_password: {{ .Values.ocbrm.db.pipelineschemapass }}

  #BRM Server Wallet Password 
  client_wallet_password: {{ .Values.ocbrm.wallet.client }}

  #BRM Server Wallet Password 
  server_wallet_password: {{ .Values.ocbrm.wallet.server }}

  #BRM Root Wallet Password 
  root_wallet_password: {{ .Values.ocbrm.wallet.root }}

  #DO NOT CHANGE
  old_client: QzFnMmIzdTQ=
  #DO NOT CHANGE
  old_root: QzFnMmIzdTQ=

  brm_crypt_key: {{ .Values.ocbrm.brm_crypt_key }}

  #SID password for dm_fusa
  dmf_sid_pwd: {{ .Values.ocbrm.dm_fusa.deployment.dmf_sid_pwd }}
  
  #PID password for dm_fusa
  dmf_pid_pwd: {{ .Values.ocbrm.dm_fusa.deployment.dmf_pid_pwd }}

  # quantum_db_password : pin
  quantum_db_password: cGlu

  # LDAP Directory server password
  ldap_server_password: {{ .Values.ocbrm.dm_ldap.deployment.dirserverpassword }}
