apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ocbc.bc.service.name }}
    namespace: {{ .Release.Namespace }}
    label:
        app.kubernetes.io/name: {{ .Values.ocbc.bc.labels.name }}
        app.kubernetes.io/version: {{ .Values.ocbc.bc.labels.version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    selector:
        app.kubernetes.io/name: {{ .Values.ocbc.bc.labels.name }}
    ports:
    {{- if eq .Values.ocbc.bc.configEnv.isSSLEnabled true }}
    -   name: ocbc-port-https
        port: {{ .Values.ocbc.bc.configEnv.httpsPort }}
        protocol: TCP
        {{- if eq .Values.ocbc.bc.configEnv.isAdminPortEnabled true }}
    -   name: ocbc-port-admin
        port: {{ .Values.ocbc.bc.configEnv.adminPort }}
        protocol: TCP
        {{- end }}
    {{- else }}
    -   name: ocbc-port-http
        port: {{ .Values.ocbc.bc.configEnv.httpPort }}
        protocol: TCP
    {{- end }}
    type: {{ .Values.ocbc.bc.service.type }}
